# Generated by Django 5.1.2 on 2024-10-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Performers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open_manhole", "Открытый люк на дороге"),
                    ("electricity_outage", "Отключение электричества"),
                    ("consultation", "Консультация по компетенции"),
                    ("garbage_collection", "Вывоз ТБО (либо уборка после)"),
                    ("courtyard_cleaning", "Уборка дворов (сан. очистка)"),
                    ("waste_removal", "Вывоз валки"),
                    ("branch_removal", "Вывоз веток"),
                    ("irrigation_repair", "Ремонт и содержание автополива"),
                    ("lighting_issue", "Освещение не работает"),
                    ("street_cleaning", "Уборка улиц (сан. очистка)"),
                    ("sanitary_pruning", "Санитарная обрезка"),
                    ("tree_felling", "Валка сухих/аварийных деревьев"),
                    ("playground_repair", "Ремонт детских элементов"),
                    ("other", "Другие вопросы"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="task",
            name="observers",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Не начато"),
                    ("in progress", "В работе"),
                    ("done", "Завершено"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performer",
                to="crm.performers",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="observers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observers",
                to="crm.observers",
            ),
        ),
    ]
