# Generated by Django 5.1.2 on 2024-10-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_observers_performers_task_category_task_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performers",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
